runtime: python311
entrypoint: uvicorn backend.main:app --host=0.0.0.0 --port=8080

instance_class: F2

env_variables:
  # Spotify
  SPOTIFY_ID: "546e581977c0466bbce76931991aacd0"
  SPOTIFY_SECRET: "fa086320033b494cabaacf987bdfcc5d"

  # Spotipy
  SPOTIPY_CLIENT_ID: "546e581977c0466bbce76931991aacd0"
  SPOTIPY_CLIENT_SECRET: "fa086320033b494cabaacf987bdfcc5d"
  SPOTIPY_REDIRECT_URI: "https://sinatra-453804.ue.r.appspot.com/callback"

  # Tidal
  TIDAL_ID: "f8bDtD6J4Z8PtZVn"
  TIDAL_SECRET: "163Pnmymvh8IrEiiJSLWXXnoi05PpQ0mSfAqUPDuRlA="
  TIDAL_REDIRECT_URI: "https://sinatra-453804.ue.r.appspot.com/tidal-callback"

  # MongoDB
  MONGODB_URI: "mongodb+srv://amborn02:o9a2zuk9H4dGK556@cluster1.gw0b0jk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

  # Other
  NODE_ENV: "production"
  MUSIC_PLATFORM: "spotify"
  PROD_URL: "https://sinatra-453804.ue.r.appspot.com"
  LOCAL_URL: "http://localhost:8000"
  PORT: "3000"

handlers:
  - url: /static
    static_dir: static

  - url: /js
    static_dir: frontend/js

  - url: /.*
    script: auto