# .github/workflows/python-tests.yml
name: Run Tests + Format + Coverage

on:
  push:        { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    # 👇 makes secrets available to every step as plain env vars
    env:
      SPOTIFY_CLIENT_ID:     ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      MONGO_URI:             ${{ secrets.MONGODB_URI }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # ✨ create a disposable .env for libraries that auto‑load it (e.g., python‑dotenv)
    - name: Write .env file
      run: |
        cat <<EOF > .env
        SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
        SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
        TIDAL_TOKEN=${TIDAL_TOKEN}
        MONGO_URI=${MONGO_URI}
        JWT_SECRET=${JWT_SECRET}
        EOF

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pytest pytest-cov

    - name: Format code with Black (dry run)
      run: black . --check --diff

    - name: Run tests with coverage
      run: pytest backend/tests --cov=backend --cov-report=xml --maxfail=1 --disable-warnings -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        slug: CourtimusPrime/Sinatra