# .github/workflows/python-tests.yml
name: Run Tests + Format + Coverage

on:
  push:
    branches: [main, optimising-http]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.0"]

    env:
      SPOTIFY_CLIENT_ID:     ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIPY_CLIENT_ID:     ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIPY_REDIRECT_URI:  ${{ secrets.SPOTIPY_REDIRECT_URI }}
      MONGO_URI:             ${{ secrets.MONGODB_URI }}
      TIDAL_TOKEN:           ${{ secrets.TIDAL_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Write .env file
      run: |
        cat <<EOF > .env
        SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
        SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
        SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
        SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
        SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
        MONGO_URI=${MONGO_URI}
        TIDAL_TOKEN=${TIDAL_TOKEN}
        EOF

    - name: Debug: check .env contents
      run: cat .env | sed 's/=.*/=[REDACTED]/'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Format code with Black (dry run)
      run: black . --check --diff

    - name: Run tests with coverage
      run: pytest backend/tests --cov=backend --cov-report=xml --maxfail=1 --disable-warnings -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        slug: CourtimusPrime/Sinatra